name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Repo info
        run: |
          echo "Repository: ${{ gitea.repository }}"
          echo "Branch: ${{ gitea.ref_name }}"
          echo "Commit: ${{ gitea.sha }}"
